package model;

public enum AgeRange {
     ZERO, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, TEN, ELEVEN, TWELVE, THIRTEEN, FOURTEEN, FIFTEEN, SIXTEEN, SEVENTEEN, EIGHTEEN, NINETEEN, TWENTY, TWENTYONE, TWENTYTWO, TWENTYTHREE, TWENTYFOUR, TWENTYFIVE, TWENTYSIX, TWENTYSEVEN, TWENTYEIGHT, TWENTYNINE, THIRTY, THIRTYONE, THIRTYTWO, THIRTYTHREE, THIRTYFOUR, THIRTYFIVE, THIRTYSIX, THIRTYSEVEN, THIRTYEIGHT, THIRTYNINE, FORTY, FORTYONE, FORTYTWO, FORTYTHREE, FORTYFOUR, FORTYFIVE, FORTYSIX, FORTYSEVEN, FORTYEIGHT, FORTYNINE, FIFTY, FIFTYONE, FIFTYTWO, FIFTYTHREE, FIFTYFOUR, FIFTYFIVE, FIFTYSIX, FIFTYSEVEN, FIFTYEIGHT, FIFTYNINE, SIXTY, SIXTYONE, SIXTYTWO, SIXTYTHREE, SIXTYFOUR, SIXTYFIVE, SIXTYSIX, SIXTYSEVEN, SIXTYEIGHT, SIXTYNINE, SEVENTY, SEVENTYONE, SEVENTYTWO, SEVENTYTHREE, SEVENTYFOUR, SEVENTYFIVE, SEVENTYSIX, SEVENTYSEVEN, SEVENTYEIGHT, SEVENTYNINE, EIGHTY, EIGHTYONE, EIGHTYTWO, EIGHTYTHREE, EIGHTYFOUR, EIGHTYFIVE, EIGHTYSIX, EIGHTYSEVEN, EIGHTYEIGHT, EIGHTYNINE, NINETY, NINETYONE, NINETYTWO, NINETYTHREE, NINETYFOUR, NINETYFIVE, NINETYSIX, NINETYSEVEN, NINETYEIGHT, NINETYNINE, HUNDRED;

     public static AgeRange calcRange(byte age){
            if(age >= 0 && age <= 100){
                return AgeRange.values()[age];
            }
            return null;
        }

        public static void main(String[] args) {
            System.out.println(AgeRange.calcRange((byte) 25));
        }

}
